### ISSUE TITLE
 Governance is Contrary to Bitcoin's Purpose

### ISSUE THREAD

**Issue by BitcoinErrorLog** [bitcoin-cap/bcap#26]
Bitcoin's purpose is to resist change—its design relies on a decentralized, consensus-driven resistance to alterations, which helps ensure its robustness and security. Any attempts to organize governance, whether through stakeholder hierarchies or formalized processes, inherently risk undermining this very resilience. By establishing governance structures, power consolidates, making Bitcoin more vulnerable to centralization and censorship.

Bitcoin is designed to minimize trust through incentive alignment, ensuring the system is both resilient and hard to change. Introducing formal governance reintroduces trust and decision-making power to human actors, which inherently increases opportunities for coercion and corruption—opposing Bitcoin’s core principle of minimizing trusted intermediaries.

The equilibrium that Bitcoin maintains emerges because changes require overwhelming consensus, which maximizes the cost of any alteration. Formalized governance mechanisms lower this cost by concentrating decision-making, making it easier for well-resourced actors to influence or capture the system. Maintaining decentralized equilibrium, where actors are disincentivized to make arbitrary changes, is key to maintaining robustness.

In Bitcoin, distinguishing between a beneficial change, a naive speculative risk, and a malicious intent is often impossible. What seems like an improvement to one stakeholder could appear as a threat to another, particularly when differing incentives are at play. Introducing more governance only amplifies these subjective disagreements, turning the process into a power struggle. Instead of naturally filtering out bad ideas through decentralized consensus, formal governance introduces a mechanism that can be captured, directed, and ultimately wielded for control.

BCAP’s treatment of governance risks missing Bitcoin's core philosophy—that more governance implies more opportunities for centralization, coercion, and censorship. Bitcoin thrives on minimizing trust and resisting organized control, and efforts to formalize governance contradict these foundational principles.

Your ability to describe, specify, and assess the market from your own perspective is inherently flawed, requiring all speculative changes to Bitcoin to be oppressive, engineer-driven forced updates to ignorant trusting users. Be appropriately humble about this power.

**Comment by moneyball** [comment]
I agree with your view but need help seeing how it applies to BCAP. It is a
non-goal of BCAP to be bitcoin's governance or to be prescriptive about
consensus changes. The only use of the term "governance" is explicitly
saying bitcoin doesn't have governance. Namely, "Bitcoin consensus change
is not achieved through formal governance but through a complex interplay
of actions and reactions among stakeholders"

Can you point out specific areas where BCAP strays from this and risks the
point you're making?

**Comment by BitcoinErrorLog** [comment]
All speculative changes to Bitcoin require governance; they are an oppressive abuse of user trust.

I fundamentally disagree with the naive concepts of "building consensus", convenient appeals to "game theory", and all speculative complexity, and feel such perspectives are ignored, which, to me, says a lot about motives. 

To me, BCAP presents as an attempt to codify the system through a biased set of narratives, ultimately serving a purpose of templating that can be referenced in arguments for changes to Bitcoin.

My ideal, responsible version of this document would be starkly more conservative, cautionary, and using only accepted economic and network dynamic concepts. 

I know most of the people involved meant well, but the conservative rational views required for this are missing, and people like Eric Voskuil should have been leading/consulting on this.

**Comment by moneyball** [comment]
> "speculative changes"

What makes a change speculative? Or rather, what is a non-speculative change?

> "more conservative"

Can you point out examples of where BCAP is too progressive or aggressive?

> "more cautionary"

The one future scenario soft fork is dedicated to being cautionary. It describes how we could wind up with a fragile network as a cautionary tale to avoid it. Where and how would you suggest more caution?

> "using only accepted economic and network dynamic concepts"

Which accepted economic and network dynamic concepts would you like to see added?

**Comment by moneyball** [comment]
> "speculative changes"

What makes a change speculative? Or rather, what is a non-speculative change?

> "more conservative"

Can you point out examples of where BCAP is too progressive or aggressive?

> "more cautionary"

The one future scenario soft fork is dedicated to being cautionary. It describes how we could wind up with a fragile network as a cautionary tale to avoid it. Where and how would you suggest more caution?

> "using only accepted economic and network dynamic concepts"

Which accepted economic and network dynamic concepts would you like to see added?

**Comment by BitcoinErrorLog** [comment]
A **speculative change** is the kind based on (imaginary) game theory and "incentive-compatibility" or other non-data-driven excuses for change. Such changes attempt to predict the future with loose undefined/theoretical models, and often obnoxious degrees of complexity that we could have no hope of assessing second-order effects of.

The opposite could be a "substantiated" change, or "evidence-based" or such, where an overwhelming amount of research and data is shown to prove the demand, appropriateness, and fitness for a specific change. Non-speculative changes should be responses to evident problems that threaten core functionality, rather than a desire to iterate or experiment.

> Can you point out examples of where BCAP is too progressive or aggressive?

Maybe start with the entire framing that defaults to entertaining new features instead of questioning if they should exist at all. (Try feeding all my comments into AI and having it review the doc, I'm not going to make pull requests here.) 

> The one future scenario soft fork is dedicated to being cautionary. It describes how we could wind up with a fragile network as a cautionary tale to avoid it. Where and how would you suggest more caution?

Caution isn’t about one chapter of concern; it’s about every step having a presumption of resistance, and every proposal being an attack on consensus. BCAP could be explicit about this.

> Which accepted economic and network dynamic concepts would you like to see added?

I'm not an expert in either, so I might suggest finding some; I just know enough from Cryptoeconomics and other Systems experience to see that there is a higher academic and axiomatic way to approach these topics. You at least have many actual game theory concepts that could be specified and presented as proofs. You at least have Cryptoeconomics and the author willing to respond to questions.

**Comment by moneyball** [comment]
I agree BCAP should not be framed in a way that suggests changing bitcoin is the default. However, I don't agree that it is framed that way. I am sure there are specific wordings we could change to improve, but I don't see any of them suggested in this issue. Don't see anything actionable so will close.
